name = "search"
type = "javascript"
account_id = '5c8575d2cd69a265380d094f0fcdf5d6'
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true

[build]
command = "yarn && yarn build"
[build.upload]
format = "service-worker"
